In [26]:
with open('sentences.txt') as f:
    content = f.readlines()
content = [x.lower() for x in content] 

In [28]:
print(content[1])

as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.



In [29]:
import re
content = [re.split('[^a-z]', t) for t in content]
print(content[0])

['in', 'comparison', 'to', 'dogs', '', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', '', '']


In [40]:

a = 0
for words in content:
    for word in words:
        if word == '':
            words.remove('')
            a += 1
print(a)   
print(words)

0
['the', 'fifth', 'major', 'update', 'to', 'mac', 'os', 'x', 'leopard', 'contains', 'such', 'a', 'mountain', 'of', 'features', 'more', 'than', 'by', 'apple', 's', 'count']


In [46]:
print(content[10])

['cat', 'command', 'is', 'one', 'of', 'the', 'basic', 'commands', 'that', 'you', 'learned', 'when', 'you', 'started', 'in', 'the', 'unix', 'linux', 'world']


In [47]:
dictionary = {}
k = 0
for words in content:
    for word in words:
        if not (word in dictionary.keys()):
            dictionary.update({word: k})
            k += 1

print(dictionary)

{'in': 0, 'comparison': 1, 'to': 2, 'dogs': 3, 'cats': 4, 'have': 5, 'not': 6, 'undergone': 7, 'major': 8, 'changes': 9, 'during': 10, 'the': 11, 'domestication': 12, 'process': 13, 'as': 14, 'cat': 15, 'simply': 16, 'catenates': 17, 'streams': 18, 'of': 19, 'bytes': 20, 'it': 21, 'can': 22, 'be': 23, 'also': 24, 'used': 25, 'concatenate': 26, 'binary': 27, 'files': 28, 'where': 29, 'will': 30, 'just': 31, 'sequence': 32, 'a': 33, 'common': 34, 'interactive': 35, 'use': 36, 'for': 37, 'single': 38, 'file': 39, 'is': 40, 'output': 41, 'content': 42, 'standard': 43, 'hear': 44, 'sounds': 45, 'too': 46, 'faint': 47, 'or': 48, 'high': 49, 'frequency': 50, 'human': 51, 'ears': 52, 'such': 53, 'those': 54, 'made': 55, 'by': 56, 'mice': 57, 'and': 58, 'other': 59, 'small': 60, 'animals': 61, 'one': 62, 'people': 63, 'deliberately': 64, 'tamed': 65, 'artificial': 66, 'selection': 67, 'they': 68, 'were': 69, 'useful': 70, 'predators': 71, 'vermin': 72, 'domesticated': 73, 'its': 74, 'closest': 

In [51]:

import numpy

# array = [[0] * len(words)] * len(tokens)
array = numpy.zeros((len(content), len(dictionary)))

print(len(content))
print(len(dictionary))
#print(array)

count = 0
for i, words in enumerate(content):
    for word in words:
        array[i][dictionary.get(word)] += 1
        count += 1

print(count)
print(array)

22
254
484
[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]]


In [56]:
import math
distances = [1]

bottomA = 0
for i in range(0, len(dictionary)):
    bottomA += array[0][i] * array[0][i]
    
bottomA = math.sqrt(bottomA)
print("bottomA = ", bottomA)

for i in range(1, len(content)):
    top = 0
    bottomB = 0
    
    for j in range(0, len(dictionary)):
        top += array[0][j] * array[i][j]
        bottomB += array[i][j] * array[i][j]
        
    bottomB = math.sqrt(bottomB)
    ans = top / (bottomA*bottomB)
    distances.append(ans)
    
print(distances)

max1 = -1
max2 = -1
ind1 = -1
ind2 = -1
for i in range(1, len(content)):
    if distances[i] >= max1:
        max2 = max1
        ind2 = ind1
        max1 = distances[i]
        ind1 = i
        
print("The closest sentence is number", ind1 + 1, ". The second closest is number", ind2 + 1)

bottomA =  3.7416573867739413
[1, 0.0472455591261534, 0.1355261854357877, 0.10482848367219183, 0.22291128503014115, 0.05976143046671968, 0.2672612419124244, 0.07412493166611013, 0.11572751247156894, 0.0944911182523068, 0.16718346377260587, 0.11952286093343936, 0.16035674514745463, 0.12964074471043288, 0.12598815766974242, 0.05572782125753529, 0.15936381457791915, 0.043355498476206004, 0.05572782125753529, 0.11145564251507058, 0.15724272550828775, 0.17496355305594133]
The closest sentence is number 7 . The second closest is number 5
